version: '3.7'

volumes:
  demo_node_modules:

services:
  demo_app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - demo_node_modules:/app/node_modules
    networks:
      - sk-issuer-service
networks:
  sk-issuer-service:
    driver: bridge
