version: '3.7'

volumes:
  demo_node_modules:

services:
  demo_app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - demo_node_modules:/app/node_modules
    networks:
      - kyc-chain-monorepo_kycc
  mongoui:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=docker.for.mac.localhost
    networks:
      - kyc-chain-monorepo_kycc
    ports:
      - '8082:8081'
networks:
  kyc-chain-monorepo_kycc:
    external: true
