apiVersion: v1
kind: Service
metadata:
    name: {{include "skis.fullname" .}}
    labels:
        app.kubernetes.io/name: {{include "skis.name" .}}
        helm.sh/chart: {{include "skis.chart" .}}
        app.kubernetes.io/instance: {{.Release.Name}}
        app.kubernetes.io/managed-by: {{.Release.Service}}
spec:
    type: {{.Values.service.type}}
    ports:
        - port: {{.Values.service.port}}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{include "skis.name" .}}
        app.kubernetes.io/instance: {{.Release.Name}}
